### ISSUE TITLE
Lost compatibility with ruby <= 1.9 ?

### ISSUE THREAD

**Issue by abriel** [funzoneq/dnsmadeeasy-rest-api#15]
Hi,

In the lib/dnsmadeeasy-rest-api.rb you use object `#<URI::HTTPS:0x0000000271d2a0>` to pass to `Net::HTTP::Get.new`.
With this I got exception:

```
/opt/chef/embedded/lib/ruby/1.9.1/net/http.rb:1861:in `initialize': undefined method `empty?' for #<URI::HTTPS:0x0000000271d2a0> (NoMethodError)
    from /opt/chef/embedded/lib/ruby/1.9.1/net/http.rb:2094:in `initialize'
    from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/dnsmadeeasy-rest-api-1.0.4/lib/dnsmadeeasy-rest-api.rb:153:in `new'
```

Thanks.

**Comment by webervin** [comment]
this should be won't fix because of https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/

**Comment by abriel** [comment]
For example, your library can be used (and using) from chef recipes. Most time, chef package from opscode comes with embedded ruby that is usual obsolete. The latest version of chef-client 11.18 has ruby 1.9.3.
Thanks.

**Comment by funzoneq** [comment]
Ruby 1.9.3 has been depricated for a long time now. Won't fix.
