### ISSUE TITLE
Better case handling needed

### ISSUE THREAD

**Issue by corwinstephen** [funzoneq/dnsmadeeasy-rest-api#3]
A lot of the methods used here rely on other methods to generate request strings. Because of that, there are some pretty common cases (like making a `records_for` request for a domain that doesn't exist) where our response is a webserver error (returned in HTML format, not JSON) and we fail out on `JSON.parse`.

My feeling is that in this case, at the very least, we should throw a "DomainNotFound" error, or even better, just fail gracefully by returning nil.

Happy to submit some pull requests if you guys will work with me on this.

**Comment by abriel** [comment]
I think in many times it is temporary error from an API server.
Could it be better to wrap it in begin .. try ? a few times at least before final raise.
Thanks.

**Comment by corwinstephen** [comment]
My issue was resolved by https://github.com/funzoneq/dnsmadeeasy-rest-api/pull/5
