### ISSUE TITLE
Disabling OpenSSL verification

### ISSUE THREAD

**Issue by marlonoso** [funzoneq/dnsmadeeasy-rest-api#9]
*api.sandbox.dnsmadeeasy.com* has an expired certificate and trying to get domains, throws this error
`OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed`
Even applying the dirty `OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE` approach

It would be good if we could disable OpenSSL verification

**Comment by acorncom** [comment]
Believe this can be closed as well ...

**Comment by funzoneq** [comment]
Yeah, dnsmadeeasy installed a valid certificate. :+1:

**Comment by acorncom** [comment]
Sadly, it looks like their sandbox api has expired again.  I wondering if I am in favor of that original PR (with a default of enforcing verification mode).  From what I remember, I've run into this issue with DNS Made Easy in the past before as well ...

**Comment by acorncom** [comment]
Scratch that, looks like things are working fine, must be an issue on my end ...
